In [ ]:
import pandas as pd 
import numpy as np 
import tensorflow as tf
import keras

In [ ]:
df = pd.read_csv('/content/Book3.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
df.dtypes

name                  object
raised_amount_usd      int64
country_code          object
city                  object
funding_round_type    object
funded_at_month        int64
funded_at_year         int64
founded_at_month       int64
founded_at_Year       object
main_category         object
update_year            int64
status                object
dtype: object

In [ ]:
df['founded_at_Year'][0] = '2011'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df.head()

name  raised_amount_usd  ... update_year     status
0             480 Biomedical           17956999  ...        2019  operating
1  4D Molecular Therapeutics            6999995  ...        2019  operating
2      7 Oaks Pharmaceutical            1613014  ...        2019  operating
3        Abeona Therapeutics            8500000  ...        2019  operating
4        Abeona Therapeutics            3600000  ...        2019  operating

[5 rows x 12 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
class MultiLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [ ]:
df1 = MultiLabelEncoder(columns = ['country_code','city','funding_round_type','main_category','status']).fit_transform(df)

In [ ]:
df1.head()

name  raised_amount_usd  ...  update_year  status
0             480 Biomedical           17956999  ...         2019       3
1  4D Molecular Therapeutics            6999995  ...         2019       3
2      7 Oaks Pharmaceutical            1613014  ...         2019       3
3        Abeona Therapeutics            8500000  ...         2019       3
4        Abeona Therapeutics            3600000  ...         2019       3

[5 rows x 12 columns]

In [ ]:
X = df1.iloc[:,[1,2,3,4,5,6,7,8,9,10]].values
y = df1['status'].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy of Model is ', accuracy_score(y_test,y_pred))

Accuracy of Model is  0.78538290862637


In [ ]:
from sklearn.tree import DecisionTreeClassifier
de = DecisionTreeClassifier()
de.fit(X_train,y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred_de = de.predict(X_test)

In [ ]:
print('Accuracy of DTC Model is',accuracy_score(y_test,y_pred_de))

Accuracy of DTC Model is 0.7112216768641162


In [ ]:
a = [[400000,115,2834,21,5,2021,2,2021,274,2025],]

In [ ]:
le = LabelEncoder().fit(df['city'])

In [ ]:
le.transform(['San Francisco'])

array([2834])

In [ ]:
le1 = LabelEncoder().fit(df['funding_round_type'])

In [ ]:
le1.transform(['seed'])

array([21])

In [ ]:
le2 = LabelEncoder().fit(df['main_category'])

In [ ]:
le2.transform(['Finance'])

array([274])

In [ ]:
le3 = LabelEncoder().fit(df['status'])

In [ ]:
le3.inverse_transform([3])

array(['operating'], dtype=object)

In [ ]:
model.predict(a)

array([3])

In [ ]:
de.predict(a)

array([3])

In [ ]:
from xgboost import XGBRegressor
from lightgbm import LGBMClassifier
from sklearn import preprocessing
from sklearn.ensemble import (AdaBoostClassifier, GradientBoostingClassifier,
                              RandomForestClassifier, VotingClassifier)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, precision_score, recall_score)
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
import lightgbm as lgbm

In [ ]:
model=[]
model_name=[]


from sklearn.linear_model import LogisticRegression
model.append(LogisticRegression())
model_name.append('Logistic Regression')

from sklearn.tree import DecisionTreeClassifier
model.append(DecisionTreeClassifier())
model_name.append('Decision Tree')


from sklearn.ensemble import RandomForestClassifier
model.append(RandomForestClassifier())
model_name.append("Random Forest")

from sklearn.neighbors import KNeighborsClassifier 
model.append(KNeighborsClassifier(n_neighbors=10))
model_name.append('KNN')

from sklearn import svm
#model.append(svm.SVC(kernel='linear'))
#model_name.append('svm_linear')

# model.append( svm.SVC(kernel='rbf'))
# model_name.append('svm_rbf')

model.append(XGBClassifier())
model_name.append('xgb')

model.append(LGBMClassifier(objective='multiclass', random_state=5))
model_name.append('lgbm')

from sklearn.ensemble import AdaBoostClassifier
model.append(AdaBoostClassifier(n_estimators=50,learning_rate=1))
model_name.append('adaboost')




In [ ]:

for i in range(len(model)):
    print(model_name[i])
    model[i].fit(X_train, y_train)
    pred=model[i].predict(X_test)
    #print((pred==y_test).sum()/y_test.shape[0])
    print(accuracy_score(y_test,pred))

Logistic Regression
0.785248436764607
Decision Tree
0.7109527331405904
Random Forest
0.806293283130505
KNN
0.7738855644456397
xgb
0.7973509043232704
lgbm
0.8035366099643649
adaboost
0.7903583675115982


In [ ]:
for i in range(len(model)):
    print(model_name[i])
    model[i].fit(X_train, y_train)
    predt=model[i].predict(a)
    print(predt,le3.inverse_transform(predt))

Logistic Regression
[3] ['operating']
Decision Tree
[3] ['operating']
Random Forest
[3] ['operating']
KNN
[3] ['operating']
xgb
[3] ['operating']
lgbm
[3] ['operating']
adaboost
[3] ['operating']


In [ ]:
b = [[400000,115,2834,21,5,2021,2,2021,274,2021],]
c = [[300000,115,2834,21,5,2021,2,2021,274,2025],]
d = [[300000,115,2834,21,5,2021,2,2021,274,2021],]

In [ ]:
for i in range(len(model)):
    print(model_name[i])
    model[i].fit(X_train, y_train)
    predt=model[i].predict(b)
    print(predt,le3.inverse_transform(predt))

Logistic Regression
[3] ['operating']
Decision Tree
[3] ['operating']
Random Forest
[3] ['operating']
KNN
[3] ['operating']
xgb
[3] ['operating']
lgbm
[3] ['operating']
adaboost
[3] ['operating']


In [ ]:
for i in range(len(model)):
    print(model_name[i])
    model[i].fit(X_train, y_train)
    predt=model[i].predict(c)
    print(predt,le3.inverse_transform(predt))

Logistic Regression
[3] ['operating']
Decision Tree
[3] ['operating']
Random Forest
[3] ['operating']
KNN
[3] ['operating']
xgb
[3] ['operating']
lgbm
[3] ['operating']
adaboost
[3] ['operating']


In [ ]:
for i in range(len(model)):
    print(model_name[i])
    model[i].fit(X_train, y_train)
    predt=model[i].predict(d)
    print(predt,le3.inverse_transform(predt))

Logistic Regression
[3] ['operating']
Decision Tree
[3] ['operating']
Random Forest
[3] ['operating']
KNN
[3] ['operating']
xgb
[3] ['operating']
lgbm
[3] ['operating']
adaboost
[3] ['operating']


In [ ]:
l = [400000,'USA','San Francisco','seed',5,2021,2,2021,'Finance',2025]

In [ ]:
def encode(a):
  le = LabelEncoder().fit(df['country_code'])
  le1 = LabelEncoder().fit(df['city'])
  le2 = LabelEncoder().fit(df['funding_round_type'])
  le3 = LabelEncoder().fit(df['main_category'])
  a[1] = int(le.transform([a[1]]))
  a[2] = int(le1.transform([a[2]]))
  a[3] = int(le2.transform([a[3]]))
  a[8] = int(le3.transform([a[8]]))
  return([a,])

In [ ]:
str(le3.inverse_transform(de.predict(encode(l))))

"['operating']"